# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phil Good
email: phil.schilter@gmail.com
description: >
  Digital playground of Mr. Phil Good.
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iphilgood.ch" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Phil Good'
bio: >
  Allow me to introduce myself. My name is Phil Good and I'm a Software Engineer. I'm currently working at <a href='http://www.calydo.com'>Calydo</a> and studying part time Computer Science at the <a href='http://www.hsr.ch'>HSR</a> in Rapperswil, Switzerland.
  I like to call myself a Software Engineer with pretty awesome front-end skills. I'm passionate about fancy designs and Ruby is the language I've fallen in love since we first met. I also like my sugar with coffee and cream.
author_image: "/assets/images/author.png"
twitter_username: iphilgoodfella
github_username:  iphilgood

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
